### ISSUE TITLE
Development installation instructions and required dependencies unclear

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#27]
The CONTRIBUTING.md file doesn't actually say how to install a non-released version. Notably the required dependencies are missing, and pip install on the repo doesn't provide the needed dependencies for rose edit:

```
❯ rose edit --version
ModuleNotFoundError: No module named 'gi'
This functionality requires optional dependencies: 
(e.g. pip install metomi-rose [])
```

**Comment by jfrost-mo** [comment]
Required additional dependencies:

- [PyGObject](https://anaconda.org/conda-forge/pygobject)
- [GTK+ 3](https://anaconda.org/conda-forge/gtk3)

**Comment by oliver-sanders** [comment]
Does `pip install PyGObject` succeed or fail if GTK 3 is not installed?

**Comment by jfrost-mo** [comment]
`pip install pygobject` fails after it tries to build it from source.

<details>
<summary>Error message when building package.</summary>

```
❯ pip install pygobject
Looking in indexes: https://metoffice.jfrog.io/metoffice/api/pypi/pypi/simple
Collecting pygobject
  Downloading https://metoffice.jfrog.io/metoffice/api/pypi/pypi/packages/packages/2b/58/d34e67a79631177e3c08e7d02b5165147f590171f2cae6769502af5f7f7e/pygobject-3.50.0.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 26.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      + meson setup /var/tmp/pip-install-24vrauk4/pygobject_f89d7f0dacb6417ab60bbc299bd7deef /var/tmp/pip-install-24vrauk4/pygobject_f89d7f0dacb6417ab60bbc299bd7deef/.mesonpy-d6pvxex3 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtests=false -Dwheel=true --wrap-mode=nofallback --native-file=/var/tmp/pip-install-24vrauk4/pygobject_f89d7f0dacb6417ab60bbc299bd7deef/.mesonpy-d6pvxex3/meson-python-native-file.ini
      The Meson build system
      Version: 1.5.2
      Source dir: /var/tmp/pip-install-24vrauk4/pygobject_f89d7f0dacb6417ab60bbc299bd7deef
      Build dir: /var/tmp/pip-install-24vrauk4/pygobject_f89d7f0dacb6417ab60bbc299bd7deef/.mesonpy-d6pvxex3
      Build type: native build
      Project name: pygobject
      Project version: 3.50.0
      C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
      C linker for the host machine: cc ld.bfd 2.27-44
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python3 found: YES (/tmp/persistent/conda/envs/rose-py3/bin/python3.12)
      Found pkg-config: YES (/usr/bin/pkg-config) 0.27.1
      Run-time dependency python found: YES 3.12
      Found CMake: /usr/bin/cmake (2.8.12.2)
      WARNING: The version of CMake /usr/bin/cmake is 2.8.12.2 but version >=3.4 is required
      Run-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig and cmake)
      Not looking for a fallback subproject for the dependency gobject-introspection-1.0 because:
      Use of fallback dependencies is disabled.
      
      ../meson.build:31:9: ERROR: Dependency 'gobject-introspection-1.0' is required but not found.
      
      A full log can be found at /var/tmp/pip-install-24vrauk4/pygobject_f89d7f0dacb6417ab60bbc299bd7deef/.mesonpy-d6pvxex3/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>


If I instead only install `pygobject` from conda-forge, I get `ValueError: Namespace Gtk not available`. This can be fixed with `conda install gtk3`.

<details>
<summary>Traceback</summary>

```
❯ rose edit
Traceback (most recent call last):                                                                                                                                                                                   
  File "/tmp/persistent/conda/envs/rose-py3/bin/rose", line 33, in <module>
    sys.exit(load_entry_point('metomi-rose', 'console_scripts', 'rose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/h02/jfrost/Projects/rose/metomi/rose/rose.py", line 275, in rose
    main(
  File "/net/home/h02/jfrost/Projects/rose/metomi/rose/rose.py", line 390, in main
    exec_sub_cmd(ns, sub_cmd, cmd_args)
  File "/net/home/h02/jfrost/Projects/rose/metomi/rose/rose.py", line 188, in exec_sub_cmd
    _exec_python(
  File "/net/home/h02/jfrost/Projects/rose/metomi/rose/rose.py", line 215, in _exec_python
    fcn = load_entry_point(entry_point)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/net/home/h02/jfrost/Projects/rose/metomi/rose/rose.py", line 230, in load_entry_point
    return entry_point.load()
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/persistent/conda/envs/rose-py3/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/persistent/conda/envs/rose-py3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/net/home/h02/jfrost/Projects/rose/metomi/rose/config_editor/main.py", line 58, in <module>
    gi.require_version('Gtk', '3.0')
  File "/tmp/persistent/conda/envs/rose-py3/lib/python3.12/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

</details

**Comment by oliver-sanders** [comment]
> pip install pygobject fails after it tries to build it from source.

Good, makes life easier.

@astroDimitrios, to resolve:
* Please add a `rose_edit` section under `[options.extras_require]` in the `setup.cfg` file
* Add `pygobject` as a dependency in this new section (ideally along with a sensible minimum version).
* Add `%(rose_edit)s` to the `all` section.

The GUI will now install with either:

```console
$ pip install .[all]
$ pip install .[rose_edit]
```

---

> If I instead only install pygobject from conda-forge, I get ValueError: Namespace Gtk not available

Dammit.

@astroDimitrios, we'll resolve later by adding both `pygobject` and `gtk` as dependencies when we release the rose version with the new GUI to conda-forge.

Context:

It looks like the feedstock maintainers are resistant to add gtk3 as a dependency of pygobject because you might want to use the system provided gtk (if present).

This may make sense for some use cases, but it isn't how Conda packages are supposed to work (they should specify their dependencies right down to glibc). E.G:

* `pygraphviz` [depends on](https://github.com/conda-forge/pygraphviz-feedstock/blob/main/recipe/meta.yaml) `graphviz`.
* `pycairo` [depends on](https://github.com/conda-forge/pycairo-feedstock/blob/main/recipe/meta.yaml) `cairo`.
* `pyzmq` [depends on](https://github.com/conda-forge/pyzmq-feedstock/blob/main/recipe/meta.yaml) `zmq`.

Etc.

I think the usual way to allow users *not* to install a full environment (i.e. to incorporate externally provided dependencies) is to provide a cut-down output (like we do with `cylc-flow-base`).

Encouraging them to change might be difficult so we might just have to hardcode gtk as a dependency (ironically making it impossible to opt out of gtk installation even though that breaks was the intention of the feedstock maintainers).
