### ISSUE TITLE
Crash when adding required config with plus button

### ISSUE THREAD

**Issue by jfrost-mo** [astroDimitrios/rose#30]
When clicking on the plus to add a required variable to the configuration as so:
![Screenshot from 2024-09-20 02-09-04](https://github.com/user-attachments/assets/eee7b003-42e9-4875-9081-ad1c1877d8ec)

It crashes with the error message:
![Screenshot from 2024-09-20 02-07-49](https://github.com/user-attachments/assets/8f7bdb1c-cf08-4ff7-9cb3-3d149b88ccad)

And this traceback in the console:
```
Traceback (most recent call last):
  File "/tmp/persistent/conda/envs/rose-test/lib/python3.12/site-packages/metomi/rose/config_editor/menuwidget.py", line 149, in <lambda>
    lambda b, e: self._popup_option_menu(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/persistent/conda/envs/rose-test/lib/python3.12/site-packages/metomi/rose/config_editor/menuwidget.py", line 295, in _popup_option_menu
    option_menu.gtk_menu_popup_at_widget(button, None, None, event)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Menu' object has no attribute 'gtk_menu_popup_at_widget'
```

It also crashes with the same error when you click on the cog icon next to a setting.

**Comment by jfrost-mo** [comment]
Appears to be fixed sometime before commit 75771a3cd7e76bcefc2f85a17c805198ad41c547
